import { useEffect, useRef, useState } from 'react';
import { Lightbulb, Volume2 } from 'lucide-react';
import type { MnemonicRecord } from '@/db/types';
import { cn } from '@/lib/utils';
import { speak } from '@/lib/tts';
import { useIsDesktop } from '@/lib/useMediaQuery';
import { MobileSheet } from './MobileSheet';

interface Props {
  mnemonic: MnemonicRecord | undefined;
  variant?: 'inline' | 'floating';
}

export function MnemonicHint({ mnemonic, variant = 'floating' }: Props) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const isDesktop = useIsDesktop();

  useEffect(() => {
    if (!open || !isDesktop) return;
    function onDoc(e: MouseEvent) {
      if (!ref.current?.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener('mousedown', onDoc);
    return () => document.removeEventListener('mousedown', onDoc);
  }, [open, isDesktop]);

  if (!mnemonic) return null;

  const body = (
    <>
      <div className="flex items-center justify-between gap-2">
        <div className="font-mono text-[10px] uppercase tracking-[0.25em] text-persimmon-700 flex items-center gap-1.5">
          <Lightbulb size={11} /> mnemonic · 巧记
        </div>
        {mnemonic.ipa && (
          <code className="font-mono text-xs text-ink2">{mnemonic.ipa}</code>
        )}
      </div>
      <div className="mt-2 font-display text-base font-bold leading-snug text-ink">{mnemonic.tip}</div>
      {mnemonic.detail && (
        <p className="mt-1.5 text-xs leading-relaxed text-ink3 italic">{mnemonic.detail}</p>
      )}
      {mnemonic.examples && mnemonic.examples.length > 0 && (
        <div className="mt-3 space-y-1.5 border-t border-paper3 pt-2">
          {mnemonic.examples.slice(0, 2).map((ex, i) => (
            <div key={i} className="flex items-start gap-1.5">
              <button
                onClick={(e) => { e.stopPropagation(); speak(ex.en); }}
                className="btn-icon !h-6 !w-6 shrink-0"
                title="朗读例句"
              >
                <Volume2 size={10} />
              </button>
              <div className="min-w-0 flex-1">
                <div className="font-display text-sm font-medium text-ink leading-snug">{ex.en}</div>
                <div className="text-[11px] text-ink3 leading-snug">{ex.zh}</div>
              </div>
            </div>
          ))}
        </div>
      )}
    </>
  );

  if (variant === 'inline') {
    return (
      <div className="rounded-md border border-persimmon/30 bg-persimmon-50/40 p-3">
        {body}
      </div>
    );
  }

  return (
    <div className="relative" ref={ref}>
      <button
        onMouseEnter={() => isDesktop && setOpen(true)}
        onClick={() => setOpen((v) => !v)}
        className={cn(
          'btn-icon !h-8 !w-8 transition-colors',
          open ? 'border-persimmon text-persimmon' : 'border-persimmon/40 text-persimmon-700 hover:border-persimmon'
        )}
        title="巧记提示"
      >
        <Lightbulb size={14} />
      </button>

      {/* 桌面端：浮窗 popover */}
      {open && isDesktop && (
        <div
          onMouseLeave={() => setOpen(false)}
          className="absolute right-0 top-10 z-40 hidden w-80 origin-top-right -rotate-1 rounded-md border border-persimmon/40 bg-paper p-4 shadow-paper animate-fade-up md:block"
          style={{
            backgroundImage:
              "linear-gradient(to bottom, rgba(255,255,255,0.4), rgba(255,255,255,0)), url(\"data:image/svg+xml;utf8,<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='1.4' numOctaves='2' stitchTiles='stitch'/><feColorMatrix values='0 0 0 0 0.85 0 0 0 0 0.32 0 0 0 0 0.12 0 0 0 0.06 0'/></filter><rect width='100%25' height='100%25' filter='url(%23n)'/></svg>\")",
          }}
        >
          <div className="absolute -top-2 left-1/2 h-3 w-12 -translate-x-1/2 rotate-3 bg-persimmon-300/60 shadow-tape" />
          {body}
          <div className="mt-2 text-right font-mono text-[9px] tracking-wider text-ink3">— generated by ai</div>
        </div>
      )}

      {/* 移动端：底部抽屉 */}
      <MobileSheet open={open && !isDesktop} onClose={() => setOpen(false)} side="bottom" title="mnemonic · 巧记">
        <div className="pb-2">
          {body}
          <div className="mt-3 text-right font-mono text-[9px] tracking-wider text-ink3">— generated by ai</div>
        </div>
      </MobileSheet>
    </div>
  );
}
