import { useEffect, useRef, useState } from 'react';
import { Lightbulb } from 'lucide-react';
import type { MnemonicRecord } from '@/db/types';
import { cn } from '@/lib/utils';

interface Props {
  mnemonic: MnemonicRecord | undefined;
  /** 'inline' 用于详情面板内联展示；'floating' 用于学习页右上角悬浮按钮 */
  variant?: 'inline' | 'floating';
}

/** 编辑式脚注风格的"巧记"提示：默认只显示一个 💡 图标，hover/click 展开
 *  - 灯泡按钮带温暖描边
 *  - 展开面板像手账上贴的便签 (paper-card + 微旋转)
 */
export function MnemonicHint({ mnemonic, variant = 'floating' }: Props) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    function onDoc(e: MouseEvent) {
      if (!ref.current?.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener('mousedown', onDoc);
    return () => document.removeEventListener('mousedown', onDoc);
  }, [open]);

  if (!mnemonic) return null;

  if (variant === 'inline') {
    return (
      <div className="relative">
        <div className="rounded-md border border-persimmon/30 bg-persimmon-50/40 p-3">
          <div className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-wider text-persimmon-700">
            <Lightbulb size={11} /> ai · 巧记
          </div>
          <div className="mt-1.5 font-display text-sm font-semibold leading-snug text-ink">{mnemonic.tip}</div>
          {mnemonic.detail && <div className="mt-1 text-xs leading-relaxed text-ink2">{mnemonic.detail}</div>}
        </div>
      </div>
    );
  }

  return (
    <div className="relative" ref={ref}>
      <button
        onMouseEnter={() => setOpen(true)}
        onClick={() => setOpen((v) => !v)}
        className={cn(
          'btn-icon !h-8 !w-8 transition-colors',
          open ? 'border-persimmon text-persimmon' : 'border-persimmon/40 text-persimmon-700 hover:border-persimmon'
        )}
        title="巧记提示 (hover)"
      >
        <Lightbulb size={14} />
      </button>
      {open && (
        <div
          onMouseLeave={() => setOpen(false)}
          className="absolute right-0 top-10 z-40 w-72 origin-top-right -rotate-1 rounded-md border border-persimmon/40 bg-paper p-4 shadow-paper animate-fade-up sm:w-80"
          style={{
            backgroundImage:
              "linear-gradient(to bottom, rgba(255,255,255,0.4), rgba(255,255,255,0)), url(\"data:image/svg+xml;utf8,<svg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='1.4' numOctaves='2' stitchTiles='stitch'/><feColorMatrix values='0 0 0 0 0.85 0 0 0 0 0.32 0 0 0 0 0.12 0 0 0 0.06 0'/></filter><rect width='100%25' height='100%25' filter='url(%23n)'/></svg>\")",
          }}
        >
          {/* 胶带装饰 */}
          <div className="absolute -top-2 left-1/2 h-3 w-12 -translate-x-1/2 rotate-3 bg-persimmon-300/60 shadow-tape" />
          <div className="font-mono text-[10px] uppercase tracking-[0.25em] text-persimmon-700">
            <Lightbulb size={10} className="inline-block" /> mnemonic · 巧记
          </div>
          <div className="mt-2 font-display text-base font-bold leading-snug text-ink">{mnemonic.tip}</div>
          {mnemonic.detail && (
            <p className="mt-2 text-xs leading-relaxed text-ink2 italic">{mnemonic.detail}</p>
          )}
          <div className="mt-2 text-right font-mono text-[9px] tracking-wider text-ink3">
            — generated by ai
          </div>
        </div>
      )}
    </div>
  );
}
